name: Deploy to VPS
on: 
  push:
    branches:
        - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Kodni yuklash
      uses: actions/checkout@v4
    
    - name: SSH Kalitni sozlash
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      shell: bash
    - name: Serverga deploy qilish 
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        APP_DIR: /ci_cd
        SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
        ssh-keyscan -H $HOST >> ~/.sshknown_hosts
        ssh $SSH_USER@SSH_HOST"
          if [! -d $APP_DIR ]; then
            mkdir -p $APP_DIR
            git clone //github action url olib kelinadi// $APP_DIR
            cd $APP_DIR
            echo 'PORT = ${PORT}' > .env
          else
            cd $APP_DIR
            git pull origin main
          fi
          npm install
          npm run build
          pm2 restart ci_cd_app || pm2 start dist/main.js --name ci_cd_app
        " 
      shell: bash