name: Test
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Install
              run: npm ci
            - name: Lint
              run: npm run lint

    test:
        needs: lint
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18, 20, 22]
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - uses: action/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install
              run: npm ci
            - name: Test
              env:
                PORT: ${{secrets.PORT}}
              run: npm run test
